base_gnn:
  aggr: mean
  dropout: 0.1569426637118328
  heads: 1
  hidden_channels: 64
  layers: 1
  lr: 0.0017448759231345576
  model: GCN
batch_size: 64
dataset: Cora
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 80
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Cora_GCN_n_samples_per_class_80
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_0118a_00006
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 20
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
