base_gnn:
  aggr: gcn
  dropout: 0.6867240276088068
  heads: 1
  hidden_channels: 32
  layers: 2
  lr: 0.017667130573655744
  model: GraphSAGE
batch_size: 64
dataset: Cora
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 10
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Cora_GraphSAGE_n_samples_per_class_10
logging_config:
  use_tensorboard: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_775ba_00003
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 20
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
