alpha: 0.1
base_job_id: best_ogbn-products_nspc_10
batch_size: 64
confgnn_config:
  aggr: mean
  base_model_path: /home/$USER/graphconformal-code/outputs/ogbn-products/n_samples_per_class/10/ogbn-products/best_ogbn-products_nspc_10/basegnn_val_acc=0.5495.ckpt
  ce_weight: 0.5
  ckpt_dir: ./outputs/ogbn-products/ogbn-products_GCN_n_samples_per_class_10
  ckpt_filename: cfgnn_{val_acc:.4f}
  dropout: 0.2470100281383668
  eval_fn: aps
  fanouts:
  - 10
  - 10
  - 5
  heads: 1
  hidden_channels: 128
  label_train_fraction: 0.5
  layers: 2
  load_probs: true
  lr: 0.04530905667988827
  model: GCN
  temperature: 2.197314687301132
  train_fn: tps
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
conformal_feature_idx: null
conformal_method: tps
conformal_metrics:
- set_sizes
- coverage
- efficiency
- feature_stratified_coverage
- size_stratified_coverage
- label_stratified_coverage
- singleton_hit_ratio
- size_stratified_coverage_violation
conformal_seed: 4
dataset: ogbn-products
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 10
dataset_split_fractions:
  calib: 0.35000000000000003
  train: 0.2
  valid: 0.1
diffusion_config:
  n_iterations: 20
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
epochs: 10
job_id: ogbn-products_GCN_n_samples_per_class_10
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: conformal
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_10aa8_00004
neighborhood_config:
  k_hop_neighborhood: 2
  num_batches: 5
  use_aps_epsilon: true
  use_tps_classwise: false
  weight_function: uniform
num_workers: 18
output_dir: ./outputs
primitive_config:
  use_aps_epsilon: true
  use_tps_classwise: false
raps_config:
  n_iterations: 20
  raps_mod: false
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
resource_config:
  cpus: 18
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
use_ddp: false
