base_gnn:
  aggr: mean
  dropout: 0.12548800768783766
  heads: 1
  hidden_channels: 16
  layers: 1
  lr: 0.0003653033365102183
  model: GraphSAGE
batch_size: 64
dataset: Coauthor_Physics
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Coauthor_Physics_GraphSAGE_split_0.2_0.1
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false
    offline: true

    run_name: TorchTrainer_2bc13_00004
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 120
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
