base_gnn:
  aggr: mean
  dropout: 0.25987611048622716
  heads: 8
  hidden_channels: 512
  layers: 2
  lr: 0.00014787977912179604
  model: GAT
batch_size: 512
dataset:
  name: Flickr
dataset_dir: /users/$USER/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Flickr_GAT_split_0.2_0.1
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_be004_00005
num_workers: 25
output_dir: ./outputs
resource_config:
  cpus: 25
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
