alpha: 0.1
base_job_id: best_Coauthor_Physics_split_0.3_0.2
batch_size: 64
confgnn_config:
  aggr: mean
  base_model_path: /users/$USER/graphconformal-code/outputs/Coauthor_Physics/split/0.3_0.2/Coauthor_Physics/best_Coauthor_Physics_split_0.3_0.2/basegnn_val_acc=0.9640.ckpt
  ce_weight: 0.5
  ckpt_dir: ./outputs/Coauthor_Physics/Coauthor_Physics_GraphSAGE_split_0.3_0.2
  ckpt_filename: cfgnn_{val_acc:.4f}
  dropout: 0.2151126635959374
  eval_fn: aps
  fanouts: []
  heads: 1
  hidden_channels: 128
  label_train_fraction: 0.5
  layers: 3
  load_probs: true
  lr: 0.00018017450075483033
  model: GraphSAGE
  temperature: 6.117835148883931
  train_fn: tps
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
conformal_feature_idx: null
conformal_method: tps
conformal_metrics:
  - set_sizes
  - coverage
  - efficiency
  - feature_stratified_coverage
  - size_stratified_coverage
  - label_stratified_coverage
  - singleton_hit_ratio
  - size_stratified_coverage_violation
conformal_seed: 4
dataset:
  name: Coauthor_Physics
dataset_dir: /users/$USER/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.3
  valid: 0.2
diffusion_config:
  n_iterations: 20
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
epochs: 10
job_id: Coauthor_Physics_GraphSAGE_split_0.3_0.2
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: conformal
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_80ae9_00007
neighborhood_config:
  k_hop_neighborhood: 2
  num_batches: 5
  use_aps_epsilon: true
  use_tps_classwise: false
  weight_function: uniform
num_workers: 25
output_dir: ./outputs
primitive_config:
  use_aps_epsilon: true
  use_tps_classwise: false
raps_config:
  n_iterations: 20
  raps_mod: false
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
resource_config:
  cpus: 27
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
use_ddp: false
