alpha: 0.1
base_job_id: best_ogbn-products_nspc_40
batch_size: 64
confgnn_config:
  aggr: mean
  base_model_path: /home/$USER/graphconformal-code/outputs/ogbn-products/n_samples_per_class/40/ogbn-products/best_ogbn-products_nspc_40/basegnn_val_acc=0.6322.ckpt
  ce_weight: 0.5
  ckpt_dir: ./outputs/ogbn-products/ogbn-products_GAT_n_samples_per_class_40
  ckpt_filename: cfgnn_{val_acc:.4f}
  dropout: 0.33373543261873334
  eval_fn: aps
  fanouts:
  - 10
  - 10
  - 5
  heads: 2
  hidden_channels: 64
  label_train_fraction: 0.5
  layers: 3
  load_probs: true
  lr: 0.007993485293873545
  model: GAT
  temperature: 6.421377206988764
  train_fn: tps
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
conformal_feature_idx: null
conformal_method: tps
conformal_metrics:
- set_sizes
- coverage
- efficiency
- feature_stratified_coverage
- size_stratified_coverage
- label_stratified_coverage
- singleton_hit_ratio
- size_stratified_coverage_violation
conformal_seed: 4
dataset: ogbn-products
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 40
dataset_split_fractions:
  calib: 0.35000000000000003
  train: 0.2
  valid: 0.1
diffusion_config:
  n_iterations: 20
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
epochs: 10
job_id: ogbn-products_GAT_n_samples_per_class_40
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: conformal
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_54ac9_00000
neighborhood_config:
  k_hop_neighborhood: 2
  num_batches: 5
  use_aps_epsilon: true
  use_tps_classwise: false
  weight_function: uniform
num_workers: 10
output_dir: ./outputs
primitive_config:
  use_aps_epsilon: true
  use_tps_classwise: false
raps_config:
  n_iterations: 20
  raps_mod: false
  resplit_every_iteration: false
  tuning_fraction: 0.5
  use_aps_epsilon: true
  use_tps_classwise: false
resource_config:
  cpus: 15
  custom: {}
  gpus: 1
  nodes: 1
results_output_dir: ./conformal_results
resume_from_checkpoint: false
seed: 0
use_ddp: false
