base_gnn:
  aggr: gcn
  dropout: 0.20814621047229329
  heads: 1
  hidden_channels: 128
  layers: 2
  lr: 0.002273516124283809
  model: GraphSAGE
batch_size: 64
dataset:
  name: Coauthor_CS
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 10
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Coauthor_CS_GraphSAGE_n_samples_per_class_10
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_6db9c_00000
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 120
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
