base_gnn:
  aggr: mean
  dropout: 0.3100713234643995
  heads: 1
  hidden_channels: 32
  layers: 2
  lr: 0.010441935701619314
  model: GCN
batch_size: 64
dataset: CiteSeer
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 40
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: CiteSeer_GCN_n_samples_per_class_40
logging_config:
  use_tensorboard: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_8a8cd_00002
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 10
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
