base_gnn:
  aggr: mean
  dropout: 0.4831840437950932
  heads: 1
  hidden_channels: 128
  layers: 1
  lr: 0.0006933078006981993
  model: GCN
batch_size: 64
dataset:
  name: Coauthor_CS
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.3
  valid: 0.1
epochs: 10
job_id: Coauthor_CS_GCN_split_0.3_0.1
logging_config:
  use_tensorboard: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_d2f75_00003
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 120
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
