base_gnn:
  aggr: mean
  dropout: 0.5
  heads: 4
  hidden_channels: 128
  layers: 3
  lr: 0.001
  model: GAT
  fanouts: [10, 10, 5]
batch_size: 64
dataset:
  name: ogbn-products
dataset_dir: /users/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 10
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: ogbn-products_GAT_n_samples_per_class_10
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: false
num_workers: 25
output_dir: ./outputs
resource_config:
  cpus: 25
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
