base_gnn:
  aggr: mean
  dropout: 0.21795470064863737
  heads: 1
  hidden_channels: 128
  layers: 1
  lr: 0.005843534026510332
  model: GCN
batch_size: 64
dataset: Cora
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.2
epochs: 10
job_id: Cora_GCN_split_0.2_0.2
logging_config:
  use_tensorboard: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_d5585_00002
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 20
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
