base_gnn:
  aggr: mean
  dropout: 0.49660265775619294
  heads: 4
  hidden_channels: 64
  layers: 2
  lr: 0.008554573347169228
  model: GAT
batch_size: 64
dataset: PubMed
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 80
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: PubMed_GAT_n_samples_per_class_80
logging_config:
  use_tensorboard: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_e3ef6_00003
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 20
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
