seed: 0

base_gnn:
  model: "GAT"
  hidden_channels: 16
  heads: 1
  layers: 2
  aggr: "mean"
  lr: 0.01

logging_config:
  use_wandb: False
  wandb_config:

    log_model: False
    group: "base"
    job_type: "debug"

epochs: 10
batch_size: 256
num_workers: 1
dataset: "Cora"
resource_config:
  cpus: 20
  nodes: 1
  gpus: 1
dataset_loading_style: "split"
dataset_split_fractions:
  train: 0.3
  valid: 0.1
  calib: 0.1
output_dir: "./outputs"
dataset_dir: "./datasets"
job_id: "basegnn_cora_debug"
resume_from_checkpoint: False

