seed: 0

base_gnn:
  model: "GCN"
  hidden_channels: 16
  heads: 1
  layers: 2
  aggr: "mean"
  lr: 0.01

logging_config:
  use_wandb: True
  wandb_config:

    log_model: False
    group: "base"
    job_type: "debug"

epochs: 10
batch_size: 256
num_workers: 1
dataset: "Cora"
resource_config:
  cpus: 28
  nodes: 1
  gpus: 1
dataset_loading_style: "n_samples_per_class"
dataset_n_samples_per_class: 10
output_dir: "./outputs"
dataset_dir: "./datasets"
job_id: "basegnn_cora_nsamples_debug"
resume_from_checkpoint: True

