calib_test_equal: True
conf_expt_config:
  seed: 0
  batch_size: 64
  dataset_dir: "$HOME/graphconformal-code/datasets"
  num_workers: 25
  epochs: 10
  alpha: 0.1

  logging_config:
    use_wandb: True
    wandb_config:

      log_model: False
      group: "conformal"
      job_type: "tune"

  confgnn_config:
    model: "GCN"
    hidden_channels: 16
    heads: 1
    layers: 2
    aggr: "mean"
    lr: 0.01
    load_probs: True
 
  resource_config:
    gpus: 1
    cpus: 27
dataset: "Cora"
l_types: ["GCN", "GAT", "GraphSAGE"] # no SGC for now
tune_split_config:
  s_type: "split"
  samples_per_class: [10, 20]
  train_fracs: [0.2, 0.3]
  val_fracs: [0.1, 0.2]

n_trials_per_config: 5
tune_output_dir: "/scratch/"
num_samples: 10
metric_mode: min
metric_used: confgnn_val_eff
