base_gnn:
  aggr: lstm
  dropout: 0.6364626308516357
  heads: 1
  hidden_channels: 128
  layers: 1
  lr: 0.005832935900902911
  model: GraphSAGE
batch_size: 64
dataset:
  name: Amazon_Photos
dataset_dir: /home/$USER/Projects/graphconformal-code/datasets
dataset_loading_style: split
dataset_n_samples_per_class: null
dataset_split_fractions:
  calib: 0.35
  train: 0.3
  valid: 0.1
epochs: 10
job_id: Amazon_Photos_GraphSAGE_split_0.3_0.1
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false

    run_name: TorchTrainer_2ef06_00005
num_workers: 2
output_dir: ./outputs
resource_config:
  cpus: 4
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
