seed: 0
dataset_dir: "./datasets"
num_workers: 10

logging_config:
  use_wandb: False

neighborhood_config:
  use_aps_epsilon: True
  k_hop_neighborhood: 2
  weight_function: "uniform"
  num_batches: 5


conformal_method: "naps"
