base_gnn:
  aggr: gcn
  dropout: 0.495502057725109
  heads: 1
  hidden_channels: 16
  layers: 2
  lr: 0.014073566712103237
  model: GraphSAGE
batch_size: 64
dataset:
  name: Coauthor_Physics
dataset_dir: /home/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 10
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Coauthor_Physics_GraphSAGE_n_samples_per_class_10
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false
    offline: true

    run_name: TorchTrainer_d5464_00009
num_workers: 1
output_dir: ./outputs
resource_config:
  cpus: 120
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
