base_gnn:
  aggr: gcn
  dropout: 0.25904502030139764
  heads: 1
  hidden_channels: 256
  layers: 2
  lr: 0.0010909750341331055
  model: GraphSAGE
batch_size: 512
dataset:
  name: Flickr
dataset_dir: /users/$USER/graphconformal-code/datasets
dataset_loading_style: n_samples_per_class
dataset_n_samples_per_class: 40
dataset_split_fractions:
  calib: 0.35
  train: 0.2
  valid: 0.1
epochs: 10
job_id: Flickr_GraphSAGE_n_samples_per_class_40
logging_config:
  use_tensorboard: false
  use_terminal: false
  use_wandb: true
  wandb_config:
    group: base
    job_type: tune
    log_model: false
    offline: false

    run_name: TorchTrainer_328cb_00001
num_workers: 25
output_dir: ./outputs
resource_config:
  cpus: 25
  custom: {}
  gpus: 1
  nodes: 1
resume_from_checkpoint: false
seed: 0
